### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by danceswithcats** [OpenMediaVault-Plugin-Developers/openmediavault-letsencrypt#12]
Hi,
Could you clarify how I'd parse the {distribution} and {components} bits, please? I'm on Arrakis 4.1.3-1 

Would I type this: echo "deb https://dl.bintray.com/openmediavault-plugin-developers/arrakis 4.1.3-1" | sudo tee -a /etc/apt/sources.list 

Or simply enter it as it is, like this?

echo "deb https://dl.bintray.com/openmediavault-plugin-developers/arrakis {distribution} {components}" | sudo tee -a /etc/apt/sources.list

I'm sorry to be so dense, but I'm not very techy.

**Comment by ryecoaaron** [comment]
You would do neither.  Install omv-extras (https://forum.openmediavault.org/index.php/Thread/5549-OMV-Extras-org-Plugin/) and then you will be able install it from the plugin list.  You shouldn't add repos to your /etc/apt/sources.list file either.

**Comment by danceswithcats** [comment]
Ah! Thank you. Good thing I asked!

**Comment by AkgunFatih** [comment]
> You would do neither. Install omv-extras (https://forum.openmediavault.org/index.php/Thread/5549-OMV-Extras-org-Plugin/) and then you will be able install it from the plugin list. You shouldn't add repos to your /etc/apt/sources.list file either.

i installed the extras but there is no letsencrypt plugin in the list

**Comment by ryecoaaron** [comment]
@AkgunFatih https://forum.openmediavault.org/index.php?thread/24545-why-should-you-use-or-not-use-dockers/&postID=186122#post186122

**Comment by AkgunFatih** [comment]
> @AkgunFatih https://forum.openmediavault.org/index.php?thread/24545-why-should-you-use-or-not-use-dockers/&postID=186122#post186122

it says `openmediavault-letsencrypt - docker` ?

**Comment by AkgunFatih** [comment]
switched to Freenas
everything is better + better community

**Comment by ryecoaaron** [comment]
I only have so much time to work on plugins.  Letsencrypt had dependencies not available in Debian's repos.  So, running it in a docker is the best way forward.  The forum has many video and threads about this.

Not sure but you will soon find that the freenas community is not better.  I will take linux over freebsd any day....
