### ISSUE TITLE
OMV 5 Support

### ISSUE THREAD

**Issue by philiplb** [OpenMediaVault-Plugin-Developers/openmediavault-letsencrypt#15]
Hi,

any chance to bring this plugin back to OMV 5? It was a bit of a pain to set LetsEncrypt up via Docker and configure a ReverseProxy in front of it. And I think its a bit too complex and complicated.
The LetsEncrypt experience with OMV 4 was very nice and smooth though!

**Comment by ryecoaaron** [comment]
Probably not.  Dependencies don't stay current enough in the Debian repos and certbot needs interaction that is not possible with the plugin too often.

**Comment by philiplb** [comment]
I see. Thanks for the answer.

**Comment by ricsp** [comment]
Hi @philiplb would you be so kind as to share the steps/guide you followed? I am having problems setting a simple letsencrypt + nginx reverse proxy for transmission. It would be great if you could share a simple example.
Thanks a lot
