### ISSUE TITLE
 RSA key length to 4096

### ISSUE THREAD

**Issue by happyreacer** [OpenMediaVault-Plugin-Developers/openmediavault-letsencrypt#4]
It wuld be nice to us a  RSA key length to 4096 by default
see more details [http://forum.openmediavault.org/index.php/Thread/12452-openmediavault-letsencrypt/?postID=138402#post138402](url)

**Comment by luxflow** [comment]
I'll be busy for the next 6 months (maybe 1 year), I cannot patch anymore
maybe other developer help

**Comment by happyreacer** [comment]
@luxflow it is a half year ago, maybe can you find time? ;-)

**Comment by ryecoaaron** [comment]
I think the change might be simple.  I don't use this plugin though.  So, can you try adding the following argument to line 48 of /usr/sbin/omv-letsencrypt:
--rsa-key-size 4096

**Comment by abpostelnicu** [comment]
I've created a pull request: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-letsencrypt/pull/6

**Comment by davidh2k** [comment]
I don't think that 4096 should be the default for certificate creation.

Von meinem iPhone gesendet

**Comment by happyreacer** [comment]
@davidh2k  why? have you seen a problem?

**Comment by davidh2k** [comment]
Yes, especially for low powered systems the initial ssl handshake will be significantly slower. You can check details here: (consider raspberry pi and derivates here)

https://webmasters.stackexchange.com/questions/84838/performance-4096-bit-rsa-key-compared-to-2048-bit-rsa-key

Also note that mobile clients (phones) will also have a slower load time when accessing a site that uses a 4096 bit cert.

Also, the common consideration is that 2048bit certs are secure.

Von meinem iPhone gesendet

**Comment by ryecoaaron** [comment]
As long as that extra argument works, I am going to add a parameter to the plugin to select the length you want.

**Comment by happyreacer** [comment]
> As long as that extra argument works, I am going to add a parameter to the plugin to select the length you want.

@ryecoaaron it would be nice

**Comment by ryecoaaron** [comment]
Can I assume you tested the argument and it works correctly?

**Comment by abpostelnicu** [comment]
Yes indeed it works!

**Comment by ryecoaaron** [comment]
Thanks for the confirmation :)  I will try to add that to the plugin today.

**Comment by ryecoaaron** [comment]
Anyone want to try the updated plugin on a **non-important** system?
http://omv-extras.org/testing/openmediavault-letsencrypt_3.3_all.deb

**Comment by abpostelnicu** [comment]
I will test it tomorrow.

**Comment by happyreacer** [comment]
@ryecoaaron  the update work, but the plugin not.
error code:The property 'cron_uuid' does not exist in the model 'conf.service.letsencrypt'
`Fehler #0:
exception 'OMV\AssertException' with message 'The property 'cron_uuid' does not exist in the model 'conf.service.letsencrypt'.' in /usr/share/php/openmediavault/config/configobject.inc:71
Stack trace:
#0 /usr/share/php/openmediavault/config/configobject.inc(186): OMV\Config\ConfigObject->assertExists('cron_uuid')
#1 /usr/share/php/openmediavault/config/configobject.inc(271): OMV\Config\ConfigObject->set('cron_uuid', '9cf18ba0-cf95-4...', false)
#2 /usr/share/php/openmediavault/config/configobject.inc(233): OMV\Config\ConfigObject->setFlatAssoc(Array, false, false)
#3 /usr/share/php/openmediavault/config/database.inc(90): OMV\Config\ConfigObject->setAssoc(Array, false)
#4 /usr/share/openmediavault/engined/rpc/letsencrypt.inc(50): OMV\Config\Database->get('conf.service.le...')
#5 [internal function]: OMVRpcServiceLetsEncrypt->getSettings(NULL, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getSettings', NULL, Array)
#8 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('LetsEncrypt', 'getSettings', NULL, Array, 1)
#9 {main}`

**Comment by ryecoaaron** [comment]
You need to clear your browser cache or ctrl-shift-R.  cron_uuid was removed.

**Comment by happyreacer** [comment]
@ryecoaaron no efect

**Comment by ryecoaaron** [comment]
What is the output of omv-showkey letsencrypt | grep uuid

**Comment by happyreacer** [comment]
`      <certuuid>ba15a8f9-0080-4f32-b74d-926f447cfd03</certuuid>
 <cron_uuid>9cf18ba0-cf95-4dc3-9214-0a849dd537a0</cron_uuid>
`

**Comment by ryecoaaron** [comment]
I guess the line in the upgrade script doesn't remove it...  Let me fix that.

**Comment by happyreacer** [comment]
okay no problem, i will wait for a new version

**Comment by ryecoaaron** [comment]
Download the package again from the link above and try it.

**Comment by happyreacer** [comment]
@ryecoaaron it doesnt work. When i save the options i dont have a normal mesage with i accept or reset the changes

**Comment by ryecoaaron** [comment]
That is what it is supposed to do.  The previous behavior was wrong in my opinion.  For this plugin, when you click save, it should only save the settings (which isn't generating any config so no apply).  Only when the generate button is click should it generate a cert.

**Comment by happyreacer** [comment]
But it doesnt generate. only "finsh" is in the infobox
... and no new certificate in my SSL options

**Comment by ryecoaaron** [comment]
I didn't say the generate button worked.  That is why I need someone to test.  I was just explaining why there is no accept the changes button.  I might have to rewrite (lots of bugs) even more of this plugin.  Lots of duplicate code.  It is just a pain in the ass to test for me and a lot more time than I wanted.

**Comment by happyreacer** [comment]
i have understood. no problem. When you have a new package let me know

**Comment by ryecoaaron** [comment]
I didn't change any code but I decided to try testing it.  I added the dry run flag to certbot, created certs and put them in /etc/letsencrypt/live/domain.com/.  All of the code for the plugin works well.

**Comment by happyreacer** [comment]
okay, i test it again. 
- made a cert with the pluginversion 3.2 with a 2048 key.
- I updated the plugin
- deactivate all reverenc from the cert
- klick to generate the new cert with the 4096 option. 
- it works but i haven't a new cert with a 4096 key length in my SSL cert window

**Comment by ryecoaaron** [comment]
Do you have a new cert in /etc/letsencrypt/live/domain.com/ after clicking the generate button?

**Comment by happyreacer** [comment]
i have a new cert in /etc/letsencrypt/live/domain.com-0001/
in /etc/letsencrypt/live/domain.com/ is my old cert

**Comment by ryecoaaron** [comment]
there’s problem. Certbot is putting it in a different directory than the plugin is looking. I will have to look to see if the directory can be specified.

**Comment by ryecoaaron** [comment]
What is the output of:  certbot certificates

**Comment by happyreacer** [comment]
What kind of output do you mean? The new cert files are right.

**Comment by ryecoaaron** [comment]
I was hoping you could run the command I posted to see if I could parse the output of that command for the plugin to determine the correct directory to copy the certs from.

**Comment by happyreacer** [comment]
sorry, my mistake!

```
`Saving debug log to /var/log/letsencrypt/letsencrypt.log

Found the following certs:
  Certificate Name: domain.com-0001
    Domains: domain.com media.domain.com  office.domain.com
    Expiry Date: 2017-12-27 19:20:50+00:00 (VALID: 89 days)
    Certificate Path: /etc/letsencrypt/live/domain.com-0001/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/domain.com-0001/privkey.pem
  Certificate Name: domain.com
    Domains: domain.com media.domain.com  office.domain.com
    Expiry Date: 2017-12-27 05:37:00+00:00 (VALID: 88 days)
    Certificate Path: /etc/letsencrypt/live/domain.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/domain.com/privkey.pem

```
`

**Comment by ryecoaaron** [comment]
That shows two certs.  Should both certs be added to the ssl cert tab in the OMV web interface?

**Comment by happyreacer** [comment]
no, i see only the domain.com in OMV web interface

**Comment by ryecoaaron** [comment]
even though domain.com-0001 is newer?

**Comment by happyreacer** [comment]
Yes it's newer and it ist not in the web interface

**Comment by ryecoaaron** [comment]
I'm confused...  Should both domain.com and domain.com-0001 be in the web interface or just domain.com-0001?  With the current plugin code, only domain.com would be added and not domain.com-0001.

**Comment by happyreacer** [comment]
I think both or the newer one. I'm wrong?

**Comment by ryecoaaron** [comment]
I honestly don't know which is correct.  Adding both would be easier and more accurate in the plugin.  Deleting the /etc/letsencrypt/live directory before executing certbot would be even easier but I don't know if that is a correct method.

**Comment by happyreacer** [comment]
I think normaly i change my domain and create a new cert. It is bad to can't use it with the web Interface.

**Comment by happyreacer** [comment]
I don't know,too but i think you can see all certs ist the better solution. you can delead it also over the web Interface

**Comment by ryecoaaron** [comment]
I will change the plugin to add all available certs.

**Comment by happyreacer** [comment]
Thies were great. Thank you for your time!

**Comment by ryecoaaron** [comment]
After looking at certbot manual, I came up with a few new things to try.  The --cert-name argument should fix the directory issue.  The renew command eliminates the need for the omv-letsencrypt script.  Package has been updated in the same location.

**Comment by happyreacer** [comment]
okay, thanks for your work. The only one problem was in the nginx surfer plugin. I have used the old cert and it change after i have no or another cert used and change back to the letsencrypt cert. it changed not automatic but it was not a realy problem. 
I test and think it works. 
great job!

**Comment by happyreacer** [comment]
i think it was a refresh or time efect.? on an other webside in the nginx plugin it changes without any doing

**Comment by happyreacer** [comment]
@ryecoaaron i would close the issue. Is that okay for you, too?

**Comment by ryecoaaron** [comment]
Yes, that is ok for me.

**Comment by happyreacer** [comment]
nice and thanks for your time!

**Comment by luxflow** [comment]
my personal thought on this plugin is, if you need advanced feature, just use pfsense on other physical machine or virtual one. it gives a lot flexibility.
